name: Run Jasmine Tests

on: [workflow_dispatch] # other options: push, pull_request.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '16'
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
            token: ${{ secrets.MY_TOKEN }}
            name: 'Test Results'
            reporter: 'jest-junit'
            path: 'junit-results/*.xml'